@startuml
title Class Diagram (Tanpa IoT)

class TempatSampah {
    - pin_sensor: Integer
    - pin_servo: Integer
    + setup()
    + loop()
}

class SensorInfrared {
    - pin: Integer
    + baca_status(): Boolean
}

class MotorServo {
    - pin: Integer
    - sudut: Integer
    + gerak(derajat)
}

' Hubungan
TempatSampah *-- SensorInfrared : menggunakan
TempatSampah *-- MotorServo : mengendalikan

note right of TempatSampah::loop
  Logika Loop:
  if (sensor.baca_status() == TRUE) {
      servo.gerak(90); // Buka
      delay(3000);
      servo.gerak(0);  // Tutup
  }
end note
@enduml