@startuml Activity_IR_Trash

title Activity Diagram Monitoring Sampah

start
:Sensor mendeteksi sampah;
:Kirim data ke backend;
:Proses data;
:Simpan ke database;
:User membuka dashboard;
:Tampilkan data;
stop

@enduml
