@startuml
title Activity Diagram (User - Sistem - Admin)

|Pengguna|
start
:Mendekati Tempat Sampah;
:Melambaikan Tangan;

|Sistem (Alat)|
:Sensor IR Mendeteksi Objek;
:Servo Membuka Penutup (90°);
:Delay (Tunggu 3-5 Detik);

|Pengguna|
:Membuang Sampah;

|Sistem (Alat)|
:Servo Menutup Penutup (0°);
:Simpan Log Aktivitas ke SD Card;
:Cek Kapasitas (Simulasi);

if (Sampah Penuh?) then (Ya)
  :Nyalakan Indikator LED Merah;
else (Tidak)
  :Standby (LED Hijau);
  stop
endif

|Admin (Petugas)|
:Melihat Indikator Penuh;
:Membuka Body Tempat Sampah;
:Mengangkat Plastik Sampah;
:Mengganti Plastik Baru;
:Reset Sistem / Matikan-Nyalakan;

|Sistem (Alat)|
:Sistem Kembali Standby;

stop
@enduml