@startuml Arsitektur_IR_Trash

title Arsitektur IR Trash Monitoring System

rectangle Sensor
rectangle BackendAPI
rectangle WebDashboard
database Database

Sensor --> BackendAPI : kirim data
BackendAPI --> Database : simpan data
Database --> BackendAPI : ambil data
WebDashboard --> BackendAPI : request data
BackendAPI --> WebDashboard : response data

@enduml
