@startuml Class_IR_Trash

title Class Diagram IR Trash Monitoring System

class Sensor {
  idSensor
  status
  mendeteksiSampah()
  kirimData()
}

class BackendAPI {
  menerimaData()
  memprosesData()
  mengirimData()
}

class Database {
  simpanData()
  ambilData()
}

class WebDashboard {
  tampilkanData()
  tampilkanGrafik()
}

Sensor --> BackendAPI : kirim data
BackendAPI --> Database : simpan / ambil
WebDashboard --> BackendAPI : request data
BackendAPI --> WebDashboard : response data

@enduml
