@startuml ERD_IR_Trash

title ERD IR Trash Monitoring System

entity Sensor {
  id_sensor
  lokasi
}

entity Deteksi {
  id_deteksi
  waktu
  status_sampah
}

Sensor ||--o{ Deteksi : menghasilkan

@enduml
