@startuml
title Sequence Diagram - Proses Maintenance (Admin)

actor "Admin" as Adm
participant "Tombol Power" as Switch
participant "Mikrokontroler" as MCU
participant "Indikator LED" as LED

Adm -> LED : Cek Status (Nyala Merah?)
activate LED
LED --> Adm : Konfirmasi Penuh
deactivate LED

Adm -> Switch : Matikan Alat (Power OFF)
activate Switch
Switch -> MCU : Cut Power
deactivate MCU
deactivate Switch

note right of Adm
  Admin melakukan pembersihan
  fisik & ganti plastik
end note

Adm -> Switch : Nyalakan Alat (Power ON)
activate Switch
Switch -> MCU : Supply Power
activate MCU

MCU -> MCU : Inisialisasi Sistem
MCU -> LED : Nyalakan LED Hijau (Ready)
activate LED
deactivate LED

deactivate MCU
deactivate Switch
@enduml