@startuml Sequence_IR_Trash

title Sequence Monitoring Sampah

actor User
participant WebDashboard
participant BackendAPI
participant Database

User -> WebDashboard : buka dashboard
WebDashboard -> BackendAPI : request data
BackendAPI -> Database : ambil data
Database -> BackendAPI : kirim data
BackendAPI -> WebDashboard : response data
WebDashboard -> User : tampilkan data

@enduml
