@startuml UseCase_IR_Trash

title Use Case IR Trash Monitoring System

actor User

rectangle Sistem {
  User --> (Melihat Dashboard)
  User --> (Melihat Grafik)
  User --> (Melihat Riwayat Deteksi)
  User --> (Memfilter Data Sensor)
}

@enduml
